import { IChildren } from "@/interface";
import type { Metadata } from "next";
import { Fredoka, Geist, Geist_Mono, Inter, Poppins } from "next/font/google";
import { FC } from "react";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const fredokaSans = Fredoka({
  variable: "--font-fredoka-sans",
  subsets: ["latin"],
});

const interSans = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

const poppinsSans = Poppins({
  variable: "--font-poppins-sans",
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Cook Shop",
  description: "Generated by create next app",
};

const RootLayout: FC<IChildren> = ({ children }) => (
  <html lang="en">
    <body
      className={`${geistSans.variable} ${geistMono.variable} ${fredokaSans.variable} ${poppinsSans.variable} ${interSans.variable} antialiased`}
    >
      {children}
    </body>
  </html>
);

export default RootLayout;
